### ISSUE TITLE
Please consider reorganizing so a clone provides standard directory structure

### ISSUE THREAD

**Issue by noloader** [dgraph-io/mediawiki-dgraph-skin#2]
Thanks for the hard work on the Dgraph skin. We are providing it as a skin for a [free/open source project](https://www.cryptopp.com/w/index.php?title=Special:Version).

I have a small request... Please consider providing a standard directory structure for Dgraph. That is, I want the following to "just work":

```
# LocalSettings.php
wfLoadSkin('Dgraph');
```

And the prelude:

```
cd /var/www/html/wiki/skins/
git clone https://github.com/dgraph-io/mediawiki-dgraph-skin.git Dgraph
```

As it stands, the files we need for the skin are located at `.../extensions/Dgraph/Dgraph` and they take extra work to make usable. Everything should be in the root directory so the wiki code can find it without extra work on our part. The extra work is detailed in [How do I clone a subdirectory only of a Git repository?](https://stackoverflow.com/a/13738951/608639) Git does not allow one to perform simple tasks in a simple fashion and this is no exception. Rather than trying to use Git for Dgraph, we cloned, manually copied and then deleted the clone. That means Dgraph will not be updated like the other source code.

We use about 30 Skins and 20 Extensions, and Dgraph is the only one that requires the attention.

-----

Dgraph might also be interested in [Manual:Extension registration](https://www.mediawiki.org/wiki/Manual:Extension_registration), which discusses pre-1.27 and post-1.27 skin and extension registration models.

**Comment by nischayn22** [comment]
I am busy with other things. Feel free to submit a pull request and I can help merge it.

**Comment by danielmai** [comment]
Closing this issue as this repo is now archived as per #6.
