### ISSUE TITLE
Is project still maintained?

### ISSUE THREAD

**Issue by jdlrobson** [dgraph-io/mediawiki-dgraph-skin#6]
This skin has been marked as unmaintained on https://www.mediawiki.org/wiki/Skin:Dgraph

It is currently not working with the latest version of Mediawiki.

Are new patches welcome here to fix this (I have one on my local machine), or should the skin be archived on MediaWiki.org and github.com ?

Thanks in advance for your answer!

**Comment by bucanero** [comment]
At least for Docs, here on Dgraph we are no longer using MediaWiki.
In any case, let me check internally if we can merge your PR to make this skin compatible with 1.36.

cheers!

**Comment by jdlrobson** [comment]
if you're not using it for DGraph, would it make sense to pull out the code into its own wikimedia (https:://github.com/wikimedia/) repository and find a maintainer in the MediaWiki/Wikimedia community?

**Comment by jdlrobson** [comment]
Any updates here? Would it make sense for us to fork this to the @wikimedia organization and allow community to maintain it there?

**Comment by danielmai** [comment]
@jdlrobson Dgraph Labs no longer uses MediaWiki. Is #5 what's needed to be merged to address this issue? Happy to merge it if that's the case.

Since Dgraph Labs no longer uses this theme, this repository can be archived as per your original comment if that makes the most sense.

**Comment by jdlrobson** [comment]
Provided it works for you, I'll maintain a fork at https://github.com/wikimedia/mediawiki-dgraph-skin which fixes any breaking changes. I assume you don't want me to keep sending pull requests that you have to deal with :-)

You can archive this now if you wish or update README to point to https://github.com/wikimedia/mediawiki-dgraph-skin.

**Comment by danielmai** [comment]
@jdlrobson Sounds good. I'll update the README and archive this repository.

Thanks for checking in and giving the theme a maintained home!
